- name: INSTALL DESIRED OS PACKAGES
  import_tasks: apt.yaml
  vars:
    package_list: "{{ base_packages }}"

- name: INSTALL PIP DEPENDENCIES
  pip:
    name: openshift
    state: present

# - name: INSTALL PIP REQUESTS
#   pip:
    