- name: "INSTALL ISC-DHCP-SERVER"
  apt:
    name: isc-dhcp-server

- name: CONFIGURE eth0 INTERFACE
  block:
    - name: "BACKUP ORIGINAL"
      copy:
        remote_src: yes
        src: /etc/network/interfaces.d/eth0
        dest: /etc/network/interfaces.d/eth0.bak
        mode: "0644"
      changed_when: false
      ignore_errors: true
    - name: "COPY CONFIGURATION"
      copy:
        src: templates/eth0
        dest: /etc/network/interfaces.d/eth0
        mode: "0644"

- name: CONFIGURE DHCP
  block:
    - name: BACKUP ORIGINAL
      copy:
        remote_src: yes
        src: /etc/dhcp/dhcpd.conf
        dest: /etc/dhcp/dhcpd.conf.bak
        mode: "0644"
      changed_when: false
    - name: COPY dhcpd.conf
      template:
        src: templates/dhcpd.j2
        dest: /etc/dhcp/dhcpd.conf
        mode: "0644"
    - name: SET INTERFACE FOR ISC-DHCP-SERVER
      lineinfile:
        path: /etc/default/isc-dhcp-server
        regexp: "^INTERFACESv4="
        line: INTERFACESv4="eth0"

- name: ENABLE IPV4 FORWARDING
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    sysctl_set: yes

- name: ADD IPTABLES RULES
  block:
    - name: APPEND NAT MASQUERADE
      iptables:
        table: nat
        action: append
        chain: POSTROUTING
        out_interface: wlan0
        jump: MASQUERADE
    - name: APPEND IN FROM WIFI TO ETH
      iptables:
        action: append
        chain: FORWARD
        in_interface: wlan0
        out_interface: eth0
        ctstate: RELATED,ESTABLISHED
        jump: ACCEPT
    - name: APPEND IN FROM ETH TO WIFI
      iptables:
        action: append
        chain: FORWARD
        in_interface: eth0
        out_interface: wlon0
        jump: ACCEPT

- name: INSTALL IPTABLES-PERSISTENT
  apt:
    name: iptables-persistent
    state: present
  register: iptables_persist

- name: RUN IPTABLES-SAVE
  shell: iptables-save
  when: iptables_persist.changed == true