
# - name: ENCRYPT ANSIBLE ACCOUNT PASSWORD
#   debug: 
#     msg: "{{ '{{ ansible_pass }}' | password_hash('sha512','saltyshaker789') }}"
#   register: ansible_pw
# - name: CHECK ANSIBLE USER PW
#   debug:
#     var: ansible_pw

- name: ADD USER {{ user_name }}
  user:
    name: "{{ user_name }}"
    # password: "{{ '{{ ansible_pw.msg }}' | password_hash('sha512','saltyshaker789') }}"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
  notify: SET PASSWD
# - debug:
#     var: user_add

- name: ALLOW USER {{ user_name }} SSH ACCESS
  lineinfile:
    path: /etc/ssh/sshd_config
    regex: '^#AllowUsers'
    line: 'AllowUsers {{ user_name }} root'
    state: present
  notify: RESTART SSHD

- name: INSTALL SUDO
  apt:
    name: sudo
    update_cache: yes

- name: ADD {{ user_name }} TO SUDOERS.D
  lineinfile:
    path: /etc/sudoers.d/{{ user_name }}
    line: '{{ user_name }} ALL=(ALL:ALL) NOPASSWD:ALL'
    state: present
    create: true
    mode: '0644'

- name: COPY SSH KEYS TO {{ user_name }} ACCOUNT
  authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"