- name: ADD CRIO KEYS
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ crio_apt_keys }}"

- name: ADD CRIO APT REPOSITORIES
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ crio_apt_repos }}"

- name: INSTALL LIBSECCOMP2
  apt:
    name: libseccomp2
    default_release: buster-backports
    state: latest

- name: INSTALL CRIO PACKAGES
  include_tasks: apt.yaml
  vars:
    package_list: "{{ crio_packages }}"

- name: USE DISTRO'S RUNC (OPTIONAL)
  blockinfile:
    path: /etc/crio/crio.conf.d
    create: true
    mode: '0644'
    block: |
      [crio.runtime.runtimes.runc]
      runtime_path = ""
      runtime_type = "oci"
      runtime_root = "/run/runc"
  when: use_distro_runc | bool


- name: CONFIGURE CGROUP_MANAGER FOR CRIO
  blockinfile:
    path: /etc/crio/crio.conf.d/02-cgroup-manager.conf
    create: true
    mode: '0644'
    block: |
      [crio.runtime]
      conmon_cgroup = "pod"
      cgroup_manager = "cgroupfs"
  register: cgroup_conf_result

- name: START & ENABLE CRI-O SERVICE
  systemd:
    name: crio
    state: started
    enabled: yes